name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - uses: actions/checkout@v4
      - run: ls
      - uses: docker/build-push-action@v6.13.0
      - run: docker images
